### PR TITLE
Make it compile

### PR DESCRIPTION
**Pull request by xibo**
At least with Qt-5.7, QByteArray to const char * conversion needs to be made
explicitly.

### CODE REVIEW

**Comment by tcberner** [comment]
Hi there

Against which version is this? kf-kdnssd-5.41 build fine here on current. Did it break on 10?

mfg Tobias

**Comment by xibo** [comment]
Hi

It's built against 11-STABLE r326700. This is the first of the error messages I'm getting:

`[107/114] /usr/bin/c++  -DKF5DNSSD_EXPORTS -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_FROM_BYTEARRAY -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_NO_SIGNALS_SLOTS_KEYWORDS -DQT_NO_URL_CAST_FROM_STRING -DQT_USE_FAST_OPERATOR_PLUS -DQT_USE_QSTRINGBUILDER -D_LARGEFILE64_SOURCE -Isrc -I/usr/ports/dns/kf5-kdnssd/work/kdnssd-5.41.0/src -Isrc/KF5DNSSD_autogen/include -I. -I/usr/local/include -isystem /usr/local/include/qt5 -isystem /usr/local/include/qt5/QtNetwork -isystem /usr/local/include/qt5/QtCore -isystem /usr/local/lib/qt5/mkspecs/freebsd-clang -isystem /usr/local/include/qt5/QtDBus -O2 -pipe -fstack-protector -fno-strict-aliasing -std=c++0x -fno-operator-names -fno-exceptions -Wno-gnu-zero-variadic-macro-arguments -Wall -Wextra -Wcast-align -Wchar-subscripts -Wformat-security -Wno-long-long -Wpointer-arith -Wundef -Wnon-virtual-dtor -Woverloaded-virtual -Werror=return-type -Wvla -Wdate-time -fdiagnostics-color=always -pedantic -O2 -pipe -fstack-protector -fno-strict-aliasing -fPIC -fvisibility=hidden -fvisibility-inlines-hidden   -fPIC -std=gnu++11 -MD -MT src/CMakeFiles/KF5DNSSD.dir/mdnsd-remoteservice.cpp.o -MF src/CMakeFiles/KF5DNSSD.dir/mdnsd-remoteservice.cpp.o.d -o src/CMakeFiles/KF5DNSSD.dir/mdnsd-remoteservice.cpp.o -c /usr/ports/dns/kf5-kdnssd/work/kdnssd-5.41.0/src/mdnsd-remoteservice.cpp
FAILED: src/CMakeFiles/KF5DNSSD.dir/mdnsd-remoteservice.cpp.o
/usr/bin/c++  -DKF5DNSSD_EXPORTS -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_FROM_BYTEARRAY -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_NO_SIGNALS_SLOTS_KEYWORDS -DQT_NO_URL_CAST_FROM_STRING -DQT_USE_FAST_OPERATOR_PLUS -DQT_USE_QSTRINGBUILDER -D_LARGEFILE64_SOURCE -Isrc -I/usr/ports/dns/kf5-kdnssd/work/kdnssd-5.41.0/src -Isrc/KF5DNSSD_autogen/include -I. -I/usr/local/include -isystem /usr/local/include/qt5 -isystem /usr/local/include/qt5/QtNetwork -isystem /usr/local/include/qt5/QtCore -isystem /usr/local/lib/qt5/mkspecs/freebsd-clang -isystem /usr/local/include/qt5/QtDBus -O2 -pipe -fstack-protector -fno-strict-aliasing -std=c++0x -fno-operator-names -fno-exceptions -Wno-gnu-zero-variadic-macro-arguments -Wall -Wextra -Wcast-align -Wchar-subscripts -Wformat-security -Wno-long-long -Wpointer-arith -Wundef -Wnon-virtual-dtor -Woverloaded-virtual -Werror=return-type -Wvla -Wdate-time -fdiagnostics-color=always -pedantic -O2 -pipe -fstack-protector -fno-strict-aliasing -fPIC -fvisibility=hidden -fvisibility-inlines-hidden   -fPIC -std=gnu++11 -MD -MT src/CMakeFiles/KF5DNSSD.dir/mdnsd-remoteservice.cpp.o -MF src/CMakeFiles/KF5DNSSD.dir/mdnsd-remoteservice.cpp.o.d -o src/CMakeFiles/KF5DNSSD.dir/mdnsd-remoteservice.cpp.o -c /usr/ports/dns/kf5-kdnssd/work/kdnssd-5.41.0/src/mdnsd-remoteservice.cpp
/usr/ports/dns/kf5-kdnssd/work/kdnssd-5.41.0/src/mdnsd-remoteservice.cpp:85:9: error: no matching function for call to 'DNSServiceResolve'
    if (DNSServiceResolve(&ref, 0, 0, d->m_serviceName.toUtf8(), d->m_type.toLatin1().constData(),
        ^~~~~~~~~~~~~~~~~
/usr/local/include/dns_sd.h:1616:31: note: candidate function not viable: no known conversion from 'QByteArray' to 'const char *' for 4th argument
DNSServiceErrorType DNSSD_API DNSServiceResolve
                              ^
1 error generated.
ninja: build stopped: subcommand failed.
*** Error code 1

Stop.
make[1]: stopped in /usr/ports/dns/kf5-kdnssd
*** Error code 1

Stop.
make: stopped in /usr/ports/dns/kf5-kdnssd`

**Comment by tcberner** [comment]
Weird, it builds fine in my 11.1-RELEASE-p1 jail.

Do you use the MDNSRESPONDER option? The header file [/usr/local/include/dns_sd.h] it complains about is form net/mDNSResponder, right?

**Comment by tcberner** [comment]
... yep, broken with mDNSResonder.

**Comment by xibo** [comment]
Indeed, the file is from mDNSResponder. As we don't communicate the ports OPTION to cmake (yet), it being installed is good enough for kdnssd to attempt using it, even if Avahi is selected instead.

**Comment by xibo** [comment]
Should explode with some noice now rather than silently ignoring the OPTIONs.
